#!/usr/bin/env bash

export XDG_CONFIG_HOME='.tests/xdg/config'
export XDG_STATE_HOME='.tests/xdg/local/state'
export XDG_DATA_HOME='.tests/xdg/local/share'
export XDG_CACHE_HOME='.tests/xdg/cache'

nvim -u "${XDG_CONFIG_HOME}/${NVIM_APPNAME:-nvim}/init.lua" -l $@
exit_code=$?

exit $exit_code
