---
on: [push, pull_request]
name: lint-test

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check lua

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-versions: ["stable", "nightly"]
    name: test
    steps:
      - uses: extractions/setup-just@v1

      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1.5"

      - name: checkout
        uses: actions/checkout@v3

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: run tests
        run: just test
